services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "${API_PORT}:8000"
    command: /app/start.sh
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    networks:
      - backend

networks:
  backend:
    driver: bridge
